Friend Module MOD_MOBILE_SETTING

#Region "プルダウン初期化"
    Friend Sub SUB_INIT_COMMBO_BOX_KIND(ByRef CMB_INIT As System.Windows.Controls.ComboBox)
        Dim STR_ITEMS() As String

        ReDim STR_ITEMS(0)
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "Chat")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "Keyboard")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "Mouse")

        Call SUB_REFRESH_COMBO_ITEM_WPF(CMB_INIT, STR_ITEMS)
    End Sub

    Public Sub SUB_INIT_COMMBO_BOX_KEY_MASK(ByRef CMB_INIT As System.Windows.Controls.ComboBox)
        Dim STR_ITEMS() As String

        ReDim STR_ITEMS(0)
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "None")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "Alt")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "Ctrl")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "Shift")

        Call SUB_REFRESH_COMBO_ITEM_WPF(CMB_INIT, STR_ITEMS)
    End Sub

    Public Sub SUB_INIT_COMMBO_BOX_KEY(ByRef CMB_INIT As System.Windows.Controls.ComboBox)

        Dim STR_ITEMS() As String
        ReDim STR_ITEMS(0)
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "None")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "1")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "2")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "3")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "4")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "5")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "6")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "7")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "8")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "9")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "0")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "-")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "^")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F1")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F2")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F3")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F4")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F5")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F6")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F7")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F8")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F9")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F10")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F11")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F12")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "A")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "B")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "C")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "D")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "E")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "F")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "G")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "H")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "I")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "J")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "K")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "L")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "M")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "N")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "O")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "P")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "Q")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "R")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "S")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "T")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "U")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "V")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "W")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "X")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "Y")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "Z")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[0]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[1]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[2]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[3]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[4]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[5]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[6]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[7]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[8]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[9]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[*]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[+]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[-]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[.]")
        Call GPOSE_ASSIST_LIB.FUNC_APPEND_STRING_ARRAY(STR_ITEMS, "NumPad[/]")

        Call SUB_REFRESH_COMBO_ITEM_WPF(CMB_INIT, STR_ITEMS)
    End Sub
#End Region

#Region "内部処理"

    Public Sub SUB_REFRESH_COMBO_ITEM_WPF(ByRef CMB_REFRESH As System.Windows.Controls.ComboBox, ByRef STR_ROW() As String)
        Dim intSELECTED_INDEX As Integer

        intSELECTED_INDEX = CMB_REFRESH.SelectedIndex '退避
        Call CMB_REFRESH.Items.Clear()

        For i = 1 To (STR_ROW.Length - 1)
            Call CMB_REFRESH.Items.Add(STR_ROW(i))
        Next

        If CMB_REFRESH.Items.Count > intSELECTED_INDEX Then
            CMB_REFRESH.SelectedIndex = intSELECTED_INDEX
        End If

    End Sub
#End Region

End Module
