Module MOD_CONST

#Region "CONFIG"
    Public Const CST_APP_CONFIG_PROCESS_NAME As String = "PROCESS_NAME"

    Public Const CST_APP_CONFIG_SAVE_DIRECTORY As String = "SAVE.DIRECTORY"

    Public Const CST_APP_CONFIG_SAVE_FILE_DIRECTORY As String = "SAVE.FILE.DIRECTORY"
    Public Const CST_APP_CONFIG_SAVE_FILE_NAME As String = "SAVE.FILE.NAME"
    Public Const CST_APP_CONFIG_SAVE_FILE_TYPE As String = "SAVE.FILE.TYPE"
    Public Const CST_APP_CONFIG_SAVE_FILE_QUALITY As String = "SAVE.FILE.QUALITY"
    Public Const CST_APP_CONFIG_SAVE_FILE_COPYRIGHT As String = "SAVE.FILE.COPYRIGHT"
    Public Const CST_APP_CONFIG_SAVE_FILE_INDEX As String = "SAVE.FILE.INDEX"

    Public Const CST_APP_CONFIG_GUIDE_LOCATION_ALIGNMENT As String = "GUIDE.LOCATION.ALIGNMENT"

    Public Const CST_APP_CONFIG_TRIM_LOCATION_LEFT As String = "TRIM.LOCATION.LEFT"
    Public Const CST_APP_CONFIG_TRIM_LOCATION_TOP As String = "TRIM.LOCATION.TOP"
    Public Const CST_APP_CONFIG_TRIM_SIZE_WIDTH As String = "TRIM.SIZE.WIDTH"
    Public Const CST_APP_CONFIG_TRIM_SIZE_HEIGHT As String = "TRIM.SIZE.HEIGHT"
    Public Const CST_APP_CONFIG_TRIM_ASPECT_RATIO_TYPE As String = "TRIM.ASPECT_RATIO.TYPE"
    Public Const CST_APP_CONFIG_TRIM_COMPOTION_TYPE As String = "TRIM.COMPOTION.TYPE"
    Public Const CST_APP_CONFIG_TRIM_COMPOTION_USER As String = "TRIM.COMPOTION.USER"

    Public Const CST_APP_CONFIG_CAMERA_CONTROL_WAIT_FOR_GAME_RESPONSE As String = "CAMERA.CONTROL.WAIT_FOR_GAME_RESPONSE"
    Public Const CST_APP_CONFIG_CAMERA_CONTROL_WASD_PUSH_WEIGHT As String = "CAMERA.CONTROL.WASD_PUSH_WEIGHT"
    Public Const CST_APP_CONFIG_CAMERA_CONTROL_ARROW_PUSH_WEIGHT As String = "CAMERA.CONTROL.ARROW_PUSH_WEIGHT"
    Public Const CST_APP_CONFIG_CAMERA_CONTROL_PAGEUD_PUSH_WEIGHT As String = "CAMERA.CONTROL.PAGEUD_PUSH_WEIGHT"

    Public Const CST_APP_CONFIG_TRIM_COMPOTION_USER_ITEM_COUNT As Integer = 9
#End Region

End Module
